name: realtime-chat

services:
  websocket_server:
    build: websocket_server
    ports:
      - "5001:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      KAFKA_BROKER: kafka-1:9092
      PUBLIC_KEY_PATH: "/code/app/keys/public_key.pem"
      ALGORITHM: "RS256"
    volumes:
      - ./auxiliar/keys:/code/app/keys:ro
    depends_on:
      - relational_database

  login_server:
    build: login_server
    ports:
      - "5002:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    depends_on:
      - relational_database
    environment:
      PRIVATE_KEY_PATH: "/code/app/keys/private_key.pem"
      PUBLIC_KEY_PATH: "/code/app/keys/public_key.pem"
      ALGORITHM: "RS256"
      DATABASE_URL: "postgresql://root:password@relational_database:5433/chatdb"
    volumes:
      - ./auxiliar/keys:/code/app/keys

  
  relational_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    volumes:
      - ./relational_database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - kafka-cluster_kafka-cluster-network

  
networks:
  kafka-cluster_kafka-cluster-network:
    external: true

volumes:
  postgres_data: